blank_issues_enabled: true
contact_links:
  - name: misty Support
    url: https://t.me/best_friends_chatting_grup
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Yukki.tech/
    about: Documentation for getting started with bot.
